### PR TITLE
Use different package feeds for MIPSr1 and MIPSr2 routers

### PR DESCRIPTION
**Pull request by ryzhovau**

### CODE REVIEW

**Comment by panther7** [comment]
Thanks for solution, btw, what are different versus http://entware.wl500g.info/binaries/entware and http://entware.wl500g.info/binaries/mipselsf/ ? I am using mipselsf on my WL500W.

**Comment by ryzhovau** [comment]
[entware](http://entware.wl500g.info/binaries/entware) use an on-chip floating point unit while [mipselsf](http://entware.wl500g.info/binaries/mipselsf/) emulate FPU in software.

**Comment by panther7** [comment]
Ok, and what is better? Entware? :)

**Comment by ryzhovau** [comment]
On one hand, it's better to use hardware units when it's available, on the other hand - it can be cause of performance degradation. http://www.linksysinfo.org/index.php?threads/using-fpu-emulator.69940/

Use any feed you wish, it's hard to find out any differences between feeds in real life on WL500W.

**Pull request merged**
